name: 代码检查

on:
  push:
    paths:
      - '**.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        python -m pip install flake8 black

    - name: Check code formatting
      run: |
        black --check .

    - name: Flake8 Lint
      uses: py-actions/flake8@v2
