# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# docs https://docs.github.com/zh/actions/writing-workflows/workflow-syntax-for-github-actions

name: Workflow

on:
  push:
    paths:
      - 'src/**.py'

env:
  OPENAI_API_KEY: OPENAI_API_KEY
  AZURE_OPENAI_API_KEY: AZURE_OPENAI_API_KEY
  ARK_API_KEY: ARK_API_KEY
  DPSK_API_KEY: DPSK_API_KEY
  CLAUDE_API_KEY: CLAUDE_API_KEY
  MINIMAX_API_KEY: MINIMAX_API_KEY
  VOLC_ACCESSKEY: VOLC_ACCESSKEY
  VOLC_SECRETKEY: VOLC_SECRETKEY
  SG_PROXY_USER: SG_PROXY_USER
  SG_PROXY_PASSWD: SG_PROXY_PASSWD

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        if [ -d tests ]; then python -m unittest discover -s tests -v; fi
